### ISSUE TITLE
Failed to get gates data 151695

### ISSUE THREAD

**Issue by zoezoevp** [Pigotka/ha-cc-jablotron-cloud#21] opened 2024-06-19 07:41 UTC
Hi,

V 0.6.1

The integration shows the following error : Failed setup, will retry: Failed to get gates data 151695.

2024-06-19 09:36:39.199 DEBUG (MainThread) [custom_components.jablotron_cloud] Preparing Jablotron data update coordinator
2024-06-19 09:36:41.341 DEBUG (MainThread) [custom_components.jablotron_cloud] Failed to get gates data for service 151695
2024-06-19 09:36:41.342 DEBUG (MainThread) [custom_components.jablotron_cloud] Finished fetching Jablotron Cloud data in 2.142 seconds (success: False)

For completeness (if related), I have two homes on the same account.

Best regards,,

Manu

**Comment by Pigotka** [comment] 2024-06-19 09:20
Duplicate of #20 
New release 0.6.2 drafted to address the issue.

**Closed by Pigotka** 2024-06-19 09:20 UTC
