### ISSUE TITLE
error while arming/disarming the alarm

### ISSUE THREAD

**Issue by adek1990** [Pigotka/ha-cc-jablotron-cloud#19] opened 2024-05-18 13:03 UTC
error while arming/disarming the alarm

Core 2024.5.4
Supervisor 2024.05.1
Operating System 12.2

2024-05-18 14:57:50.479 WARNING (SyncWorker_2) [homeassistant.helpers.frame] Detected that custom integration 'jablotron_cloud' calls async_write_ha_state from a thread at custom_components/jablotron_cloud/alarm_control_panel.py, line 160: self.async_write_ha_state(), please report it to the author of the 'jablotron_cloud' custom integration
2024-05-18 14:57:50.480 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140587662372800] Unexpected exception
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
response = await hass.services.async_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
response_data = await coro
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
return await target(service_call)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
single_response = await _handle_entity_call(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
result = await task
^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 175, in async_alarm_disarm
await self.hass.async_add_executor_job(self.alarm_disarm, code)
File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/jablotron_cloud/alarm_control_panel.py", line 160, in alarm_disarm
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1008, in async_write_ha_state
self.hass.verify_event_loop_thread("async_write_ha_state")
File "/usr/src/homeassistant/homeassistant/core.py", line 440, in verify_event_loop_thread
frame.report(
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 162, in report
_report_integration(what, integration_frame, level, error_if_integration)
File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 203, in _report_integration
raise RuntimeError(
RuntimeError: Detected that custom integration 'jablotron_cloud' calls async_write_ha_state from a thread at custom_components/jablotron_cloud/alarm_control_panel.py, line 160: self.async_write_ha_state(). Please report it to the author of the 'jablotron_cloud' custom integration.

**Comment by Pigotka** [comment] 2024-05-18 18:25
Duplicate of #18

**Closed by Pigotka** 2024-05-18 18:25 UTC
